[package]
name = "make-mikan-os-kernel"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootimage = "0.10"

[profile.release]
panic = "abort" # カーネルや組み込みシステムではpanic時のスタックアンワインドを無効にする
lto = true # リンク時最適化を有効にする

[profile.dev]
panic = "abort"